run:
  timeout: 20m


linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  fast: true

linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        allow:
          - github.com/aleksander-git/data-analyzer

issues:
  exclude-rules:
    - path: _grpc/gen\.go
      linters:
        - linters-all