// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package datasets

import (
	"database/sql"
	"time"
)

// YDBs
type Database struct {
	// Database id (autoincrement)
	DatabaseID int64
	// In case we need to use different storages or versions
	Type string
	// Storage name
	Name string
	// Description
	Descr sql.NullString
	// Connection string to connect to storage
	Dsn sql.NullString
	// Connection token
	Token sql.NullString
}

// Datasets
type Dataset struct {
	// Dataset id (autoincrement)
	DatasetID int64
	// Owner of dataset
	UserID int64
	// Status id
	DatasesetStatusID int32
	// Database id
	DatabaseID int64
	// Name of the table
	TableName sql.NullString
	// Dataset is archieved (deleted)
	IsArchieved bool
	// When dataset was archieved
	ArchievedAt sql.NullTime
	// When dataset was created
	CreatedAt time.Time
}

// List of available dataset statuses
type DatasetStatus struct {
	// Status id
	DatasesetStatusID int32
	// Status name (uploading, available, failed)
	Name string
	// Status description
	Descr sql.NullString
}

// User list
type User struct {
	// User Id (autoincrement)
	UserID int64
	// Unique user text identificator
	Username string
	// Password hash
	PasswordHash sql.NullString
	// Person Name
	Name sql.NullString
	// Person Surname
	Surename sql.NullString
	// Email address
	Email sql.NullString
	// Messenger addresses
	Messengers sql.NullString
	// When user record was added
	CreatedAt time.Time
	// User record is archieved (deleted)
	IsArchieved bool
	// When user was archieved
	ArchievedAt sql.NullTime
	// User account is blocked
	IsBlocked bool
	// When user account was blocked
	BlockedAt sql.NullTime
	// Number of times user entered incorrect password
	IncorrectPwdTryCount int32
}
